-- safe divide, returns 0 if b is 0
DROP FUNCTION IF EXISTS SafeDiv;
DELIMITER ..
CREATE FUNCTION SafeDiv(IN a INT, IN b INT)
RETURNS FLOAT DETERMINISTIC
BEGIN
    IF b = 0 THEN 
        RETURN 0;
    END IF;
    RETURN a / b;
END ..
DELIMITER ;
