-- safe divide, returns 0 if b is 0

DROP FUNCTION IF EXISTS SafeDiv;
DELIMITER ..
CREATE FUNCTION SafeDiv(a INT, b INT)
DETERMINISTIC
RETURNS FLOAT
BEGIN
    IF b = 0 THEN 
        RETURN 0;
    END IF;
    RETURN a / b;
END ..
DELIMITER ;
